version: "3.9"
services:
    blogserver:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./:/Blog/
        command: "npm run dev"
    postgresdockerdashboard:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports:
            - 5435:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
        driver: local
