version: "3.9"
services:
    blogserver:
        build:
            context: .
            dockerfile: Dockerfile.build
        ports:
            - 3000:3000
        volumes:
            - ./:/app/
        command: "npm run start"
    blogPosts:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        expose:
            - "5433" # Publishes 5433 to other containers but NOT to host machine
        ports:
            - 5435:5433
        volumes:
            - blogposts:/var/lib/postgresql/data2
volumes:
    blogposts:
        driver: local
networks:
    default:
        external:
            name: gstreet
