version: "3.9"
services:
    blogserver:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./:/Blog/
        command: "npm run dev"
    postgresdockerBlog:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports:
            - 5435:5432
        volumes:
            - loginDBVolume:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8088:8080
        links:
            - postgresdockerBlog
volumes:
    loginDBVolume:
        external: true
