version: "3.9"
services:
    blogserver:
        env_file:
            - dev.env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./:/Blog/
        command: "npm run dev --reload"
    blogPosts:
        env_file:
            - dev.env
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        # expose:
        #     - "5434" # Publishes 5433 to other containers but NOT to host machine
        ports:
            - 5435:5434
        volumes:
            - blogposts:/var/lib/postgresql/data
volumes:
    blogposts:
        driver: local
networks:
    default:
        external:
            name: gstreet
